### ISSUE TITLE
Please branch stable-22.08

### ISSUE THREAD

**Issue by tim77** [flathub/org.winehq.Wine.DLLs.dxvk#7]
Please made new branch `branch/stable-22.08`.

**Comment by gasinvein** [comment]
We should've published to just `stable` branch, because DXVH has no ABI dependency on the runtime, but oh well, I guess it's too late to change the branch naming scheme and we'll have to create a new one for every new runtime.

**Comment by pm4rcin** [comment]
@gasinvein couldn't something be done about that? What would it require to make it work? What about even creating it but with different name since current name seems a bit off from the rest as wine is not dxvk's official page?
